# Generated by Django 4.2.7 on 2023-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='nam_product',
            new_name='nama_product',
        ),
    ]
