# Generated by Django 3.2 on 2023-12-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20231222_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formlogin',
            old_name='email',
            new_name='username',
        ),
    ]
