# Generated by Django 3.2 on 2023-12-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_email_formlogin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_product', models.CharField(max_length=225)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
            ],
        ),
    ]
