# Generated by Django 3.2 on 2023-12-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_pembelian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pembelian',
        ),
    ]
