# Generated by Django 3.2 on 2023-12-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_delete_pembelian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
