# Generated by Django 3.2 on 2023-12-22 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_formlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('menu', 'Menu'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='menu', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
